# Site settings
title: GRN36909's Blog
# the protocol and hostname of your site, eg. `http://laobubu.github.io`
url: "https://grn36909.github.io"
# the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
baseurl: ""
#
#timezone: Asia/Chongqing
description: >
  One or more sentences introducing this blog.

# Your information
email: your_email@example.com
author: grn36909
avatar: "//grn36909.github.io/assets/main/user.jpg"
profile: jekyll blog 建设中.
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "mailto:your_email@example.com"
  GitHub: "https://github.com/grn36909/grn36909.github.io"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About / 关于我: /about/
    Category / 文章分类: /category/

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
